import { prisma } from "./db";
import { hashPassword, randomPassword } from "./passwords";
import { sendMail, isEmail } from "./email";

const norm = (s: unknown) => String(s ?? "").trim().toLowerCase();

/**
 * When an owner assigns an Email to a tenant unit, auto-create a tenant login
 * account (if one doesn't already exist) and email the credentials.
 * Mirrors the original serverAddUnit / serverUpdateUnitData behaviour.
 */
export async function ensureTenantAccount(opts: {
  ownerId: string;
  email: string;
  tenantName: string;
  tenantCode: string;
  currency: string;
}): Promise<void> {
  const { ownerId, email, tenantName, tenantCode, currency } = opts;
  if (!isEmail(email)) return;

  const existing = await prisma.account.findUnique({
    where: { email: norm(email) },
  });
  if (existing) return; // don't clobber an existing account

  const tempPw = randomPassword(6);
  await prisma.account.create({
    data: {
      email: norm(email),
      passwordHash: await hashPassword(tempPw),
      name: tenantName || "",
      role: "tenant",
      tier: "Free",
      currency,
      ownerId,
      linkedTenantId: tenantCode,
      mustChangePassword: true,
      note: "業主建檔自動生成",
    },
  });

  await sendMail({
    to: email,
    subject: "[物業系統通知] 您的專屬租客帳號已開通",
    body:
      `親愛的 ${tenantName} 您好：\n\n` +
      `您的業主已為您建立專屬檔案，系統自動生成了登入帳號：\n\n` +
      `👉 登入信箱：${email}\n` +
      `👉 專屬租客ID：${tenantCode}\n` +
      `👉 初始密碼：${tempPw}\n\n` +
      `首次登入時系統會要求您設定新密碼。\n\n-- 系統自動發送 --`,
  });
}

/** Next sequential invoice number for an owner, e.g. INV-2026-0001. */
export async function nextInvoiceNumber(ownerId: string): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `INV-${year}-`;
  const rows = await prisma.payment.findMany({
    where: { ownerId, invoiceNumber: { startsWith: prefix } },
    select: { invoiceNumber: true },
  });
  let max = 0;
  for (const r of rows) {
    const n = parseInt(r.invoiceNumber.split("-")[2] || "0", 10);
    if (!isNaN(n) && n > max) max = n;
  }
  return prefix + String(max + 1).padStart(4, "0");
}

export function ymNow(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export function displayMonth(ym?: string): string {
  const [y, m] = (ym || ymNow()).split("-");
  return `${y}年${parseInt(m, 10)}月`;
}

export function dateStr(): string {
  return new Date().toLocaleDateString("zh-TW");
}

type PaymentInput = {
  ownerId: string;
  tenantCode: string;
  period?: string;
  docCategory?: string;
  title: string;
  totalAmount?: number;
  paidAmount?: number;
  receiptDate?: string;
  status?: string;
  autoGenerated?: boolean;
  needEmail?: boolean;
  currency?: string;
  remark?: string;
};

/**
 * Create a payment row, assign an invoice number, and optionally email the
 * tenant. Central path used by every billing action.
 */
export async function createPayment(input: PaymentInput) {
  const invoiceNumber = await nextInvoiceNumber(input.ownerId);
  const payment = await prisma.payment.create({
    data: {
      ownerId: input.ownerId,
      tenantCode: input.tenantCode,
      createdDate: dateStr(),
      period: input.period ?? ymNow(),
      docCategory: input.docCategory ?? "帳單",
      title: input.title,
      totalAmount: input.totalAmount ?? 0,
      paidAmount: input.paidAmount ?? 0,
      receiptDate: input.receiptDate ?? "",
      status: input.status ?? "未繳費",
      currency: input.currency ?? "HK$",
      autoGenerated: input.autoGenerated ?? false,
      needEmail: input.needEmail ?? false,
      invoiceNumber,
      remark: input.remark ?? "",
    },
  });

  if (input.needEmail) {
    const unit = await prisma.unit.findFirst({
      where: { ownerId: input.ownerId, tenantCode: input.tenantCode },
    });
    if (unit?.email) {
      const isReceipt = payment.docCategory === "收據";
      const cur = payment.currency;
      await sendMail({
        to: unit.email,
        subject: isReceipt
          ? `[物業系統通知] 收款確認：${payment.title}`
          : `[物業系統通知] 您有一張新的單據：${payment.title}`,
        body:
          `親愛的 ${unit.tenantName} 您好：\n\n` +
          (isReceipt
            ? `系統已確認收到您的款項（單號：${payment.invoiceNumber}）。\n本次實收金額：${cur} ${payment.paidAmount}\n\n感謝您的繳納！`
            : `系統已為您開立新單據（單號：${payment.invoiceNumber}）。\n應繳總額：${cur} ${payment.totalAmount}\n\n請登入系統查看明細並儘速繳納。`) +
          `\n\n-- 系統自動產生 --`,
      });
    }
  }

  return payment;
}
