import { prisma } from "@/lib/db";
import { ok, adminOnly } from "@/lib/api";
import { createPayment, ymNow, displayMonth } from "@/lib/services";

function num(v: unknown): number {
  const n = parseFloat(String(v));
  return isNaN(n) ? 0 : n;
}

// Meter-reading based utility billing.
// Body: { rows: [{ tenantCode, waterCurrent, electricCurrent }] }
// For each tenant we read the unit's stored *previous* meter readings,
// compute this period's usage = current − previous, bill it at the unit's
// rate, then save the current readings as the new "previous" for next time.
export async function POST(req: Request) {
  const a = await adminOnly();
  if ("response" in a) return a.response;
  const owner = a.user;
  const { rows } = await req.json();
  const ym = ymNow();

  let created = 0;
  const results: { tenantCode: string; waterUsage: number; electricUsage: number; total: number }[] = [];

  for (const r of rows || []) {
    const unit = await prisma.unit.findFirst({
      where: { ownerId: owner.id, tenantCode: r.tenantCode },
    });
    if (!unit) continue;

    const waterCur = num(r.waterCurrent);
    const elecCur = num(r.electricCurrent);
    // usage from meter delta; never negative (handles meter reset / first entry)
    const waterUsage = Math.max(waterCur - unit.waterReading, 0);
    const elecUsage = Math.max(elecCur - unit.electricReading, 0);
    const waterAmt = waterUsage * unit.waterRate;
    const elecAmt = elecUsage * unit.electricRate;
    const total = Math.round(waterAmt + elecAmt);

    // Always store the new readings so next period's delta is correct,
    // even if we don't bill (e.g. zero usage).
    await prisma.unit.update({
      where: { id: unit.id },
      data: {
        waterReading: waterCur,
        electricReading: elecCur,
        waterUsage,
        electricUsage: elecUsage,
      },
    });

    if (total <= 0) continue;

    const cur = owner.currency;
    await createPayment({
      ownerId: owner.id,
      tenantCode: r.tenantCode,
      period: ym,
      docCategory: "帳單",
      title: `${displayMonth(ym)}水電費（水 ${waterUsage.toFixed(1)} 噸 / 電 ${elecUsage.toFixed(1)} 度）`,
      totalAmount: total,
      status: "未繳費",
      currency: cur,
      autoGenerated: true,
      remark:
        `【水費】上期 ${unit.waterReading} → 今期 ${waterCur}，` +
        `用量 ${waterUsage.toFixed(1)} 噸 × ${cur}${unit.waterRate} = ${cur}${Math.round(waterAmt).toLocaleString()}\n` +
        `【電費】上期 ${unit.electricReading} → 今期 ${elecCur}，` +
        `用量 ${elecUsage.toFixed(1)} 度 × ${cur}${unit.electricRate} = ${cur}${Math.round(elecAmt).toLocaleString()}`,
    });
    created++;
    results.push({ tenantCode: r.tenantCode, waterUsage, electricUsage: elecUsage, total });
  }
  return ok({ created, results });
}
