import { prisma } from "@/lib/db";
import { ok, adminOnly } from "@/lib/api";
import { createPayment, ymNow, displayMonth } from "@/lib/services";

// Batch-generate this month's rent bills for every occupied unit, skipping any
// that already have a rent bill for the period.
export async function POST() {
  const a = await adminOnly();
  if ("response" in a) return a.response;
  const owner = a.user;

  const ym = ymNow();
  const units = await prisma.unit.findMany({
    where: { ownerId: owner.id, tenantCode: { not: "" } },
  });
  const existing = await prisma.payment.findMany({
    where: { ownerId: owner.id, period: ym },
  });

  let created = 0,
    skipped = 0;
  for (const u of units) {
    if (!u.tenantName || u.monthlyRent <= 0) continue;
    const dup = existing.some(
      (p) => p.tenantCode === u.tenantCode && p.title.includes("租金")
    );
    if (dup) {
      skipped++;
      continue;
    }
    await createPayment({
      ownerId: owner.id,
      tenantCode: u.tenantCode,
      period: ym,
      docCategory: "帳單",
      title: `${displayMonth(ym)}租金`,
      totalAmount: u.monthlyRent,
      status: "未繳費",
      currency: owner.currency,
      autoGenerated: true,
    });
    created++;
  }
  return ok({ created, skipped });
}
